---
- hosts: k8_master
  become: true

  tasks:
    # Disable swap
    - name: Disable swap immediately
      command: swapoff -a
      
    - name: Remove swap from fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s+sw\s+.*)$'
        line: '# \1'
        backrefs: yes
        state: present
      
    # Load kernel modules
    - name: Load overlay kernel module
      community.general.modprobe:
        name: overlay
        state: present
        
    - name: Load br_netfilter kernel module
      community.general.modprobe:
        name: br_netfilter
        state: present
        
    - name: Make kernel modules persistent
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        line: "{{ item }}"
        create: yes
        state: present
      loop:
        - overlay
        - br_netfilter
    
    # Configure kernel parameters
    - name: Configure kernel parameters for Kubernetes
      blockinfile:
        path: /etc/sysctl.d/kubernetes.conf
        create: yes
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
      
    - name: Apply sysctl changes
      command: sysctl --system
    - name: Install prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
        state: present
        update_cache: false

    - name: Create keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Kubernetes repository key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /tmp/kubernetes-release.key
        mode: '0644'

    - name: Dearmor GPG key
      ansible.builtin.shell: |
        cat /tmp/kubernetes-release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Check key file permissions
      ansible.builtin.stat:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      register: key_file

    - name: Set correct permissions for key
      ansible.builtin.file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: '0644'
      when: key_file.stat.exists and key_file.stat.mode != '0644'

    - name: Add Kubernetes repository (fixed format)
      copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        mode: '0644'

    - name: Set correct permissions for repo file
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        mode: '0644'

    - name: Update apt cache
      apt:
        update_cache: true

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install kubeadm, kubelet, and kubectl
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubeadm
        - kubelet
        - kubectl

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      ignore_errors: true

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Install Calico network plugin
      become: false
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
