---
- hosts: k8_master
  become: true

  tasks:
    - name: Get primary network interface IP
      shell: hostname -I | awk '{print $1}'
      register: host_ip
      changed_when: false

    - name: Add node entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ host_ip.stdout }} k8scp"
        state: present

    - name: Create kubeadm config file
      copy:
        dest: /root/kubeadm-config.yaml
        content: |
          apiVersion: kubeadm.k8s.io/v1beta4
          kind: ClusterConfiguration
          kubernetesVersion: v1.32.3
          controlPlaneEndpoint: "{{ host_ip.stdout }}:6443"
          networking:
            podSubnet: 10.244.0.0/16
        mode: '0644'

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: true
        daemon_reload: true

    - name: Initialize Kubernetes master with config
      command: kubeadm init --config=/root/kubeadm-config.yaml --upload-certs --node-name=k8scp
      register: kubeadm_output

    - name: Save kubeadm init output
      copy:
        content: "{{ kubeadm_output.stdout }}"
        dest: /root/kubeadm-init.out
        mode: '0644'

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: true
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      ignore_errors: true

    - name: Apply Calico networking
      become: false
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      ignore_errors: true

    - name: Install bash-completion
      apt:
        name: bash-completion
        state: present

    - name: Configure kubectl bash completion
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'source <(kubectl completion bash)'
        state: present
        create: true