---
- hosts: k8_worker
  become: true
  vars:
    master_ip: "{{ hostvars[groups['k8_master'][0]]['ansible_host'] }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Add master node entry to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ master_ip }} k8scp"
        state: present

    - name: Copy join command from Ansible control node to worker
      copy:
        src: "{{ playbook_dir }}/../scripts/k8s_join_command.sh"
        dest: /tmp/k8s_join_command.sh
        mode: '0700'

    - name: Join the worker node to the cluster
      command: sh /tmp/k8s_join_command.sh
      register: join_output
      failed_when: join_output.rc != 0 and "already exists" not in join_output.stderr
      changed_when: join_output.rc == 0

    - name: Show join output
      debug:
        var: join_output.stdout_lines
      when: join_output.stdout_lines is defined
